export const imageManifest = {
  "arasgrand|main|idli": "/images/restaurants/aras-grand/main/IDLI.jpg",
  "arasgrand|main|idlivada": "/images/restaurants/aras-grand/main/IDLI VADA.jpg",
  "arasgrand|main|sheera": "/images/restaurants/aras-grand/main/SHEERA.jpg",
  "arasgrand|main|uppit": "/images/restaurants/aras-grand/main/UPPITTU.jpg",
  "arasgrand|main|dahivada": "/images/restaurants/aras-grand/main/DAHI VADA.jpg",
  "arasgrand|main|purikurma": "/images/restaurants/aras-grand/main/PURI KURMA.jpg",
  "arasgrand|main|palav": "/images/restaurants/aras-grand/main/PALAV.jpg",
  "arasgrand|main|sadadosa": "/images/restaurants/aras-grand/main/sada  dosa.jpg",
  "arasgrand|main|masaladosa": "/images/restaurants/aras-grand/main/masala dosa.jpg",
  "arasgrand|main|akkidosa": "/images/restaurants/aras-grand/main/AKKI DOSA.jpg",
  "arasgrand|main|mysoremasala": "/images/restaurants/aras-grand/main/Mysore Masala Dosa.jpg",
  "arasgrand|main|palakmasala": "/images/restaurants/aras-grand/main/PALAK MASALA.jpg",
  "arasgrand|southindiansnack|tomotoomlet": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/tomoto omlet.jpg",
  "arasgrand|main|onionuttappa": "/images/restaurants/aras-grand/main/onion uttappa.jpg",
  "arasgrand|main|ravamasaladosa": "/images/restaurants/aras-grand/main/masala dosa.jpg",
  "arasgrand|dosa|setdosa": "/images/restaurants/dwaraka/dosa/set dosa.jpg",
  "arasgrand|main|ravasadadosa": "/images/restaurants/aras-grand/main/sada  dosa.jpg",
  "arasgrand|main|cheesemasaladosa": "/images/restaurants/aras-grand/main/masala dosa.jpg",
  "arasgrand|main|paneermasaladosa": "/images/restaurants/aras-grand/main/masala dosa.jpg",
  "arasgrand|main|cheeseonionuttappa": "/images/restaurants/aras-grand/main/onion uttappa.jpg",
  "arasgrand|main|papermasaladosa": "/images/restaurants/aras-grand/main/masala dosa.jpg",
  "arasgrand|hotbeverages|tea": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/Tea.jpg",
  "arasgrand|hotbeverages|blacktea": "/images/restaurants/dwaraka/hotbeverages/black tea.jpg",
  "arasgrand|hotbeverages|specialtea": "/images/restaurants/dwaraka/hotbeverages/special tea.jpg",
  "arasgrand|snacksbeverages|coffee": "/images/restaurants/foodriders-cafe/Snacks & Beverages/Coffee.png",
  "arasgrand|hotbeverages|bournvita": "/images/restaurants/dwaraka/hotbeverages/bournvita.jpg",
  "arasgrand|hotbeverages|blackcoffee": "/images/restaurants/dwaraka/hotbeverages/black cofee.jpg",
  "arasgrand|hotbeverages|gingertea": "/images/restaurants/dwaraka/hotbeverages/ginger tea.jpg",
  "arasgrand|hotbeverages|lemontea": "/images/restaurants/dwaraka/hotbeverages/lemon tea.jpg",
  "arasgrand|hotbeverages|badammilk": "/images/restaurants/dwaraka/hotbeverages/Badam milk.jpg",
  "arasgrand|quickbites|masalapapad": "/images/restaurants/dwaraka/quickbites/Masala Papad.jpg",
  "arasgrand|quickbites|frenchfries": "/images/restaurants/dwaraka/quickbites/FRENCH FRIES.jpg",
  "arasgrand|quickbites|periperifries": "/images/restaurants/dwaraka/quickbites/PERI PERI FRIES.jpg",
  "arasgrand|salads|greensalad": "/images/restaurants/dwaraka/salads/green_salad.png",
  "arasgrand|vegstarters|vegbullet": "/images/restaurants/dwaraka/vegstarters/VEG BULLET.jpg",
  "arasgrand|vegstarters|vegcrispy": "/images/restaurants/dwaraka/vegstarters/VEG CRISPY.jpg",
  "arasgrand|specials|arasspecialchineseplatter": "/images/restaurants/aras-grand/specials/Aras Special Chinese Platter.jpg",
  "arasgrand|specials|vegspringroll": "/images/restaurants/aras-grand/specials/Veg Spring Roll.jpeg",
  "arasgrand|specials|arasspecialspringroll": "/images/restaurants/aras-grand/specials/Aras Special Spring Roll.jpeg",
  "arasgrand|specials|vegmomos": "/images/restaurants/aras-grand/specials/Veg Momos.jpeg",
  "arasgrand|specials|paneerpopcorn": "/images/restaurants/aras-grand/specials/Paneer Popcorn.jpeg",
  "arasgrand|vegstarters|babycorntikka": "/images/restaurants/dwaraka/vegstarters/BABY CORN TIKKA.jpg",
  "arasgrand|chatsitems|panipuri": "/images/restaurants/hotel-nandini-deluxe/chatsitems/Panipuri.jpg",
  "arasgrand|chatsitems|bhelpuri": "/images/restaurants/hotel-nandini-deluxe/chatsitems/Bhel puri.jpg",
  "arasgrand|chatsitems|pavbhaji": "/images/restaurants/hotel-nandini-deluxe/chatsitems/pav bhaji.jpg",
  "arasgrand|rice|onionchillyfriedrice": "/images/restaurants/dwaraka/rice/ONION CHILLI FRIED RICE.jpg",
  "arasgrand|rice|burntgarlicfriedrice": "/images/restaurants/dwaraka/rice/BURNT GARLIC FRIED RICE.jpg",
  "arasgrand|rice|paneerfriedrice": "/images/restaurants/dwaraka/rice/Paneer Fried Rice.jpg",
  "arasgrand|noodles|veghakkanoodles": "/images/restaurants/dwaraka/noodles/VEG HAKKA NOODLES.jpg",
  "arasgrand|noodles|vegschezwannoodles": "/images/restaurants/dwaraka/noodles/VEG SCHEZWAN NOODLES.jpg",
  "arasgrand|specials|arasspecial": "/images/restaurants/aras-grand/specials/Aras Special Chinese Platter.jpg",
  "arasgrand|northindian|vegpatiyala": "/images/restaurants/malasa-mangalya/northindian/veg patiyala.jpg",
  "arasgrand|tandooriitems|butterroti": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/butter roti.jpg",
  "arasgrand|tandooriitems|butternaan": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/butter naan.jpg",
  "arasgrand|biryani|vegbiriyani": "/images/restaurants/dwaraka/biryani/Veg biryani.jpg",
  "arasgrand|biryani|paneerbiriyani": "/images/restaurants/dwaraka/biryani/Paneer Biriyani.jpg",
  "arasgrand|biryani|mushroombiriyani": "/images/restaurants/dwaraka/biryani/Mashroom Biriyani.jpg",
  "arasgrand|dinner|jeerarice": "/images/restaurants/basaveshwar-khanavali/dinner/JEERA RICE.jpeg",
  "arasgrand|rice|gheerice": "/images/restaurants/dwaraka/rice/GHEE RICE.jpg",
  "arasgrand|rice|curdrice": "/images/restaurants/dwaraka/rice/Curd Rice.jpg",
  "arasgrand|freshjuicemilkshake|watermelonjuice": "/images/restaurants/hotel-nandini-deluxe/freshjuicemilkshake/Water Melon Juice.jpg",
  "arasgrand|juicemilkshakes|buttermilk": "/images/restaurants/malasa-mangalya/juicemilkshakes/butter milk.jpg",
  "arasgrand|juicemilkshakes|applemilkshake": "/images/restaurants/malasa-mangalya/juicemilkshakes/Apple milkshake.jpg",
  "arasgrand|freshjuicemilkshake|mangomilkshake": "/images/restaurants/hotel-nandini-deluxe/freshjuicemilkshake/Mango Milk Shake.jpg",
  "arasgrand|kharaandsweets|gulabjamun": "/images/restaurants/malasa-mangalya/kharaandsweets/gulab jamun.jpg",
  "basaveshwarkhanavali|dinner|": "/images/restaurants/basaveshwar-khanavali/dinner/CHAPATI UTA.jpeg",
  "davanagerebennedosecenter|specialties|idliplate": "/images/restaurants/davanagere-benne-dose-center/specialties/idli plate.jpg",
  "davanagerebennedosecenter|specialties|padduplate8piece": "/images/restaurants/davanagere-benne-dose-center/specialties/paddu.jpg",
  "dwaraka|hotbeverages|blacktea": "/images/restaurants/dwaraka/hotbeverages/black tea.jpg",
  "dwaraka|hotbeverages|specialtea": "/images/restaurants/dwaraka/hotbeverages/special tea.jpg",
  "dwaraka|hotbeverages|lemontea": "/images/restaurants/dwaraka/hotbeverages/lemon tea.jpg",
  "dwaraka|hotbeverages|gingertea": "/images/restaurants/dwaraka/hotbeverages/ginger tea.jpg",
  "dwaraka|hotbeverages|filtercoffee": "/images/restaurants/dwaraka/hotbeverages/filter cofee.jpg",
  "dwaraka|hotbeverages|blackcoffee": "/images/restaurants/dwaraka/hotbeverages/black cofee.jpg",
  "dwaraka|hotbeverages|bournvita": "/images/restaurants/dwaraka/hotbeverages/bournvita.jpg",
  "dwaraka|hotbeverages|milkplain": "/images/restaurants/dwaraka/hotbeverages/milk plain.jpg",
  "dwaraka|hotbeverages|badammilk": "/images/restaurants/dwaraka/hotbeverages/Badam milk.jpg",
  "dwaraka|breakfast|idli": "/images/restaurants/dwaraka/breakfast/idli.jpg",
  "dwaraka|breakfast|idlivada": "/images/restaurants/dwaraka/breakfast/idli vada.jpg",
  "dwaraka|breakfast|vada": "/images/restaurants/dwaraka/breakfast/Vadaa.jpg",
  "dwaraka|breakfast|uppitu": "/images/restaurants/dwaraka/breakfast/uppittu.jpg",
  "dwaraka|breakfast|shira": "/images/restaurants/dwaraka/breakfast/Shira.jpg",
  "dwaraka|breakfast|chowchowbath": "/images/restaurants/dwaraka/breakfast/Chow Chow bath.jpg",
  "dwaraka|breakfast|kurmapuri": "/images/restaurants/dwaraka/breakfast/Kurma puri.jpg",
  "dwaraka|breakfast|dahivada": "/images/restaurants/dwaraka/breakfast/Dahi vada.jpg",
  "dwaraka|breakfast|mosaravalakki": "/images/restaurants/dwaraka/breakfast/Avalakki.jpg",
  "dwaraka|breakfast|pulav": "/images/restaurants/dwaraka/breakfast/Pulav.jpg",
  "dwaraka|dosa|sadadosa": "/images/restaurants/dwaraka/dosa/sada  dosa.jpg",
  "dwaraka|dosa|masaladosagheepudi": "/images/restaurants/dwaraka/dosa/masala dosa.jpg",
  "dwaraka|dosa|mysoremasaladosa": "/images/restaurants/dwaraka/dosa/Mysore Masala Dosa.jpg",
  "dwaraka|dosa|buttermasaladosa": "/images/restaurants/dwaraka/dosa/butter masala dosa.jpg",
  "dwaraka|dosa|opendosa": "/images/restaurants/dwaraka/dosa/open dosa.jpg",
  "dwaraka|dosa|setdosa": "/images/restaurants/dwaraka/dosa/set dosa.jpg",
  "dwaraka|dosa|akkidosa": "/images/restaurants/dwaraka/dosa/akki dosa.jpg",
  "dwaraka|dosa|onionuttapa": "/images/restaurants/dwaraka/dosa/onion uttappa.jpg",
  "dwaraka|dosa|tomatoomlet": "/images/restaurants/dwaraka/dosa/tomato omlet.jpg",
  "dwaraka|dosa|ravadosa": "/images/restaurants/dwaraka/dosa/rava dosa.jpg",
  "dwaraka|dosa|paneerbuttermasaladosa": "/images/restaurants/dwaraka/dosa/butter masala dosa.jpg",
  "dwaraka|dosa|dosaidlicombosmallmasaladosaminiidliravaidly": "/images/restaurants/dwaraka/dosa/masala dosa.jpg",
  "dwaraka|combos|dosacombomasaladosaminiuttaparavadosa": "/images/restaurants/dwaraka/combos/dosa_combo.png",
  "dwaraka|salads|greensalad": "/images/restaurants/dwaraka/salads/green_salad.png",
  "dwaraka|salads|frenchsalad": "/images/restaurants/dwaraka/salads/french_salad.png",
  "dwaraka|salads|russiansalad": "/images/restaurants/dwaraka/salads/russian_salad.png",
  "dwaraka|soups|tomatosoup": "/images/restaurants/dwaraka/soups/tomato_soup.png",
  "dwaraka|soups|veghotandsoursoup": "/images/restaurants/dwaraka/soups/hot_and_sour_soup.png",
  "dwaraka|soups|sweetcornsoup": "/images/restaurants/dwaraka/soups/sweet_corn_soup.png",
  "dwaraka|soups|vegmanchowsoup": "/images/restaurants/dwaraka/soups/manchow_soup.png",
  "dwaraka|soups|vegclearsoup": "/images/restaurants/dwaraka/soups/clear_soup.png",
  "dwaraka|soups|creamofmushroom": "/images/restaurants/dwaraka/soups/cream_of_mushroom.png",
  "dwaraka|soups|creamofpalak": "/images/restaurants/dwaraka/soups/cream_of_palak.png",
  "dwaraka|soups|veghontonnoodlessoup": "/images/restaurants/dwaraka/soups/honton_noodles_soup.png",
  "dwaraka|quickbites|rostedpapad": "/images/restaurants/dwaraka/quickbites/ROSTED PAPAD.jpg",
  "dwaraka|quickbites|masalapapad": "/images/restaurants/dwaraka/quickbites/Masala Papad.jpg",
  "dwaraka|quickbites|peanutmasala": "/images/restaurants/dwaraka/quickbites/PEANUT MASALA.jpg",
  "dwaraka|quickbites|frenchfries": "/images/restaurants/dwaraka/quickbites/FRENCH FRIES.jpg",
  "dwaraka|quickbites|periperifries": "/images/restaurants/dwaraka/quickbites/PERI PERI FRIES.jpg",
  "dwaraka|quickbites|channagarlicdry": "/images/restaurants/dwaraka/quickbites/CHANNA GARLIC DRY.jpg",
  "dwaraka|paneerstarters|malaipaneertikka": "/images/restaurants/dwaraka/paneerstarters/MALAI PANEER TIKKA.jpg",
  "dwaraka|paneerstarters|paneerhariyali": "/images/restaurants/dwaraka/paneerstarters/PANEER HARIYALI.jpg",
  "dwaraka|paneerstarters|paneerpahadi": "/images/restaurants/dwaraka/paneerstarters/PANEER PAHADI.jpg",
  "dwaraka|paneerstarters|acharipaneer": "/images/restaurants/dwaraka/paneerstarters/ACHARI PANEER.jpg",
  "dwaraka|paneerstarters|paneerbanjaratikka": "/images/restaurants/dwaraka/paneerstarters/PANEER BANJARA TIKKA.jpg",
  "dwaraka|mushroomstarters|mushroomtikka": "/images/restaurants/dwaraka/mushroomstarters/MUSHROOM TIKKA.jpg",
  "dwaraka|mushroomstarters|chatpatimushroom": "/images/restaurants/dwaraka/mushroomstarters/CHATPATI MASHROOM.jpg",
  "dwaraka|mushroomstarters|mushroommultanitikka": "/images/restaurants/dwaraka/mushroomstarters/MUSHROOM MULTANI TIKKA.jpg",
  "dwaraka|vegstarters|tandoorigobi": "/images/restaurants/dwaraka/vegstarters/TANDOORI GOBI.jpg",
  "dwaraka|vegstarters|babycorntikka": "/images/restaurants/dwaraka/vegstarters/BABY CORN TIKKA.jpg",
  "dwaraka|vegstarters|vegseekkabab": "/images/restaurants/dwaraka/vegstarters/VEG SEEK KABAB.jpg",
  "dwaraka|vegstarters|cornseekkabab": "/images/restaurants/dwaraka/vegstarters/CORN SEEK KABAB.jpg",
  "dwaraka|vegstarters|vegcrispy": "/images/restaurants/dwaraka/vegstarters/VEG CRISPY.jpg",
  "dwaraka|vegstarters|vegbullet": "/images/restaurants/dwaraka/vegstarters/VEG BULLET.jpg",
  "dwaraka|vegstarters|vegspringroll": "/images/restaurants/dwaraka/vegstarters/VEG SPRING ROLLS.jpg",
  "dwaraka|vegstarters|onionpakoda": "/images/restaurants/dwaraka/vegstarters/ONION PAKODA.jpg",
  "dwaraka|vegstarters|palakpakoda": "/images/restaurants/dwaraka/vegstarters/PALAK PAKODA.jpg",
  "dwaraka|vegstarters|harabharakabab": "/images/restaurants/dwaraka/vegstarters/HARABHARA KABAB.jpg",
  "dwaraka|vegstarters|veglolipop6pieces": "/images/restaurants/dwaraka/vegstarters/VEG LOLIPOP.jpg",
  "dwaraka|gobistarters|gobichilli": "/images/restaurants/dwaraka/gobistarters/Gobi chilli.jpg",
  "dwaraka|chefspecial|paneermanchurianpaneer65": "/images/restaurants/dwaraka/chefspecial/PANNER MANCHURIAN.jpg",
  "dwaraka|noodles|americanchopsy": "/images/restaurants/dwaraka/noodles/AMERICAN CHOPSY.jpg",
  "dwaraka|noodles|veghakkanoodles": "/images/restaurants/dwaraka/noodles/VEG HAKKA NOODLES.jpg",
  "dwaraka|noodles|vegschezwannoodles": "/images/restaurants/dwaraka/noodles/VEG SCHEZWAN NOODLES.jpg",
  "dwaraka|noodles|singaporenoodleshongkongnoodles": "/images/restaurants/dwaraka/noodles/SINGAPORE NOODLES+HONGKONG NOODLES.jpg",
  "dwaraka|noodles|brownfrychillynoodles": "/images/restaurants/dwaraka/noodles/BROWN FRY CHILLI NOODLES.jpg",
  "dwaraka|chefspecial|vegfriedricepannermanchuriansmallcolddrink": "/images/restaurants/dwaraka/chefspecial/COLD DRINK.jpg",
  "dwaraka|chefspecial|vegnoodlesfriedricecolddrink": "/images/restaurants/dwaraka/chefspecial/COLD DRINK.jpg",
  "dwaraka|chefspecial|paneertikkalabadar": "/images/restaurants/dwaraka/chefspecial/PANEER TIKKA LABADAR.jpg",
  "dwaraka|chefspecial|paneerbaramati": "/images/restaurants/dwaraka/chefspecial/PANEER BARAMATI.jpg",
  "dwaraka|chefspecial|vegdeewanihandi": "/images/restaurants/dwaraka/chefspecial/VEG DEEWANI HANDI.jpg",
  "dwaraka|chefspecial|methichaman": "/images/restaurants/dwaraka/chefspecial/METHI CHAMAN.jpg",
  "dwaraka|chefspecial|kofta": "/images/restaurants/dwaraka/chefspecial/KOFTA.jpg",
  "dwaraka|chefspecial|paneerchingari": "/images/restaurants/dwaraka/chefspecial/PANEER CHINGARI.jpg",
  "dwaraka|chefspecial|paneerlahori": "/images/restaurants/dwaraka/chefspecial/PANEER LAHORI.jpg",
  "dwaraka|chefspecial|paneerustam": "/images/restaurants/dwaraka/chefspecial/PANEER USTAM.jpg",
  "dwaraka|chefspecial|dwarkaspecial3differenttypesofgravy": "/images/restaurants/dwaraka/chefspecial/DWARKA SPECIAL.jpg",
  "dwaraka|chefspecial|jaikapunjab": "/images/restaurants/dwaraka/chefspecial/JAIKA PUNJAB.jpg",
  "dwaraka|maincourse|vegtawamasala": "/images/restaurants/dwaraka/maincourse/VEG TAWA MASALA.jpg",
  "dwaraka|maincourse|vegkofta": "/images/restaurants/dwaraka/maincourse/VEG KOFTA.jpg",
  "dwaraka|maincourse|vegangara": "/images/restaurants/dwaraka/maincourse/VEG ANGARA.jpg",
  "dwaraka|maincourse|veghariyali": "/images/restaurants/dwaraka/maincourse/VEG HARIYALI.jpg",
  "dwaraka|maincourse|vegafgani": "/images/restaurants/dwaraka/maincourse/VEG AFGANI.jpg",
  "dwaraka|maincourse|vegjaipuri": "/images/restaurants/dwaraka/maincourse/VEG JAIPURI.jpg",
  "dwaraka|maincourse|vegkheemamasala": "/images/restaurants/dwaraka/maincourse/VEG KHEEMA MASALA.jpg",
  "dwaraka|northindian|vegpatiyala": "/images/restaurants/malasa-mangalya/northindian/veg patiyala.jpg",
  "dwaraka|dosa|paneerbuttermasalamakhanwala": "/images/restaurants/dwaraka/dosa/paneer butter masala.jpg",
  "dwaraka|paneerstarters|paneertikkamasala": "/images/restaurants/dwaraka/paneerstarters/PANEER TIKKA.jpg",
  "dwaraka|rice|curdrice": "/images/restaurants/dwaraka/rice/Curd Rice.jpg",
  "dwaraka|rice|spclcurdrice": "/images/restaurants/dwaraka/rice/Curd Rice.jpg",
  "dwaraka|rice|gheerice": "/images/restaurants/dwaraka/rice/GHEE RICE.jpg",
  "dwaraka|rice|onionchillyfriedrice": "/images/restaurants/dwaraka/rice/ONION CHILLI FRIED RICE.jpg",
  "dwaraka|rice|burntgarlicfriedrice": "/images/restaurants/dwaraka/rice/BURNT GARLIC FRIED RICE.jpg",
  "dwaraka|chefspecial|mushroomfriedrice": "/images/restaurants/dwaraka/chefspecial/FRIED RICE.jpg",
  "dwaraka|rice|tripleschezwanrice": "/images/restaurants/dwaraka/rice/TRIPLE SCHEZWAN RICE.jpg",
  "dwaraka|rice|paneerfriedrice": "/images/restaurants/dwaraka/rice/Paneer Fried Rice.jpg",
  "dwaraka|biryani|paneerbiryani": "/images/restaurants/dwaraka/biryani/Paneer Biriyani.jpg",
  "dwaraka|biryani|paneertikkabiryani": "/images/restaurants/dwaraka/biryani/Paneer tikka biryani.jpg",
  "dwaraka|biryani|vegbiryani": "/images/restaurants/dwaraka/biryani/Veg biryani.jpg",
  "dwaraka|biryani|hyderabadibiryani": "/images/restaurants/dwaraka/biryani/Hyderabadi biriyani.jpg",
  "dwaraka|raita|vegraita": "/images/restaurants/dwaraka/raita/Mix Veg Raita.jpg",
  "dwaraka|raita|pineappleraita": "/images/restaurants/dwaraka/raita/Pineapple Raita.jpg",
  "hundekarkhanavali|meals|chapatiuta": "/images/restaurants/hundekar-khanavali/meals/Chapati Uta.jpg",
  "hundekarkhanavali|meals|rottiuta": "/images/restaurants/hundekar-khanavali/meals/Rotti Uta.jpg",
  "hundekarkhanavali|meals|shengaholige": "/images/restaurants/hundekar-khanavali/meals/holige.jpg",
  "malasamangalya|hotbeverages|tea": "/images/restaurants/malasa-mangalya/hotbeverages/Tea.jpg",
  "malasamangalya|hotbeverages|brucoffee": "/images/restaurants/malasa-mangalya/hotbeverages/coffee.jpg",
  "malasamangalya|hotbeverages|kt": "/images/restaurants/malasa-mangalya/hotbeverages/kt.jpg",
  "malasamangalya|hotbeverages|bournvita": "/images/restaurants/malasa-mangalya/hotbeverages/bournvita.jpg",
  "malasamangalya|hotbeverages|milk": "/images/restaurants/malasa-mangalya/hotbeverages/milk.jpg",
  "malasamangalya|hotbeverages|blacktea": "/images/restaurants/malasa-mangalya/hotbeverages/black tea.jpg",
  "malasamangalya|hotbeverages|kashaya": "/images/restaurants/malasa-mangalya/hotbeverages/kashay.jpg",
  "malasamangalya|southindian|upma": "/images/restaurants/malasa-mangalya/southindian/upma.jpg",
  "malasamangalya|southindian|sheera": "/images/restaurants/malasa-mangalya/southindian/shira.jpg",
  "malasamangalya|southindian|idli": "/images/restaurants/malasa-mangalya/southindian/idli.jpg",
  "malasamangalya|southindian|vada": "/images/restaurants/malasa-mangalya/southindian/Vadaa.jpg",
  "malasamangalya|southindian|idlivada": "/images/restaurants/malasa-mangalya/southindian/idli vada.jpg",
  "malasamangalya|southindian|puri": "/images/restaurants/malasa-mangalya/southindian/puri.jpg",
  "malasamangalya|southindian|kurmapuri": "/images/restaurants/malasa-mangalya/southindian/Kurma puri.jpg",
  "malasamangalya|southindian|ricepalav": "/images/restaurants/malasa-mangalya/southindian/Pulav.jpg",
  "malasamangalya|southindian|ravaidli": "/images/restaurants/malasa-mangalya/southindian/rava idli.jpg",
  "malasamangalya|southindian|bajji": "/images/restaurants/malasa-mangalya/southindian/Bajji.jpg",
  "malasamangalya|dosa|akkidosa": "/images/restaurants/malasa-mangalya/dosa/akki dosa.jpg",
  "malasamangalya|dosa|masaladosa": "/images/restaurants/malasa-mangalya/dosa/masala dosa.jpg",
  "malasamangalya|dosa|masaladosacut": "/images/restaurants/malasa-mangalya/dosa/masala dosa.jpg",
  "malasamangalya|dosa|papermasaladosa": "/images/restaurants/malasa-mangalya/dosa/paper masala dosa.jpg",
  "malasamangalya|dosa|setdosa": "/images/restaurants/malasa-mangalya/dosa/set dosa.jpg",
  "malasamangalya|main|ravadosa": "/images/restaurants/aras-grand/main/rava dosa.jpg",
  "malasamangalya|dosa|palakdosa": "/images/restaurants/malasa-mangalya/dosa/palak dosa.jpg",
  "malasamangalya|southindian|mosaruvada": "/images/restaurants/malasa-mangalya/southindian/Vadaa.jpg",
  "malasamangalya|kharaandsweets|balusha": "/images/restaurants/malasa-mangalya/kharaandsweets/Balusha.jpg",
  "malasamangalya|kharaandsweets|mysorepak": "/images/restaurants/malasa-mangalya/kharaandsweets/mysore pak.jpg",
  "malasamangalya|pavbhaji|pavbhaji": "/images/restaurants/malasa-mangalya/pavbhaji/pav bhaji.jpg",
  "malasamangalya|pavbhaji|specialpavbhaji": "/images/restaurants/malasa-mangalya/pavbhaji/special pava bhaji.jpg",
  "malasamangalya|southindianmealsrice|extrarice": "/images/restaurants/malasa-mangalya/southindianmealsrice/extra rice.jpg",
  "malasamangalya|southindianmealsrice|extrachapati": "/images/restaurants/malasa-mangalya/southindianmealsrice/extra chapati.jpg",
  "malasamangalya|thali|chapatibhaji": "/images/restaurants/hotel-nandini-deluxe/thali/Chapati bhaji.jpg",
  "malasamangalya|southindianmealsrice|ricesambar": "/images/restaurants/malasa-mangalya/southindianmealsrice/Rice Sambar.jpg",
  "malasamangalya|tandoori|tandoorirotimeals": "/images/restaurants/malasa-mangalya/tandoori/roti.jpg",
  "malasamangalya|chats|bhelpuri": "/images/restaurants/malasa-mangalya/chats/Bhel puri.jpg",
  "malasamangalya|southindian|shevpuri": "/images/restaurants/malasa-mangalya/southindian/puri.jpg",
  "malasamangalya|chats|panipuri": "/images/restaurants/malasa-mangalya/chats/Panipuri.jpg",
  "malasamangalya|chats|dahipuri": "/images/restaurants/malasa-mangalya/chats/Dahi puri.jpg",
  "malasamangalya|salads|greensalad": "/images/restaurants/dwaraka/salads/green_salad.png",
  "malasamangalya|quickbites|masalapapad": "/images/restaurants/dwaraka/quickbites/Masala Papad.jpg",
  "malasamangalya|soup|sweetcornvegsoup": "/images/restaurants/malasa-mangalya/soup/sweet corn veg soup.jpg",
  "malasamangalya|soups|tomatosoup": "/images/restaurants/dwaraka/soups/tomato_soup.png",
  "malasamangalya|chinese|gobimanchurian": "/images/restaurants/malasa-mangalya/chinese/Gobi Manchurian.jpg",
  "malasamangalya|chinese|gobichilly": "/images/restaurants/malasa-mangalya/chinese/Gobi chilly.jpg",
  "malasamangalya|chinese|gobi65": "/images/restaurants/malasa-mangalya/chinese/Gobi 65.jpg",
  "malasamangalya|chinese|fingerchips": "/images/restaurants/malasa-mangalya/chinese/finger chips.jpg",
  "malasamangalya|chinese|paneerchilly": "/images/restaurants/malasa-mangalya/chinese/paneer chilly.jpg",
  "malasamangalya|chinese|paneermanchurian": "/images/restaurants/malasa-mangalya/chinese/paneer Manchurian.jpg",
  "malasamangalya|chinese|paneer65": "/images/restaurants/malasa-mangalya/chinese/paneer 65.jpg",
  "malasamangalya|chinese|mushroomchilly": "/images/restaurants/malasa-mangalya/chinese/mashroom chilly.jpg",
  "malasamangalya|chinese|mushroom65": "/images/restaurants/malasa-mangalya/chinese/mashroom 65.jpg",
  "malasamangalya|chinese|mushroommanchurian": "/images/restaurants/malasa-mangalya/chinese/mashroom manchurian.jpg",
  "malasamangalya|chinese|vegharabarakabab": "/images/restaurants/malasa-mangalya/chinese/veg harabara kabab.jpg",
  "malasamangalya|friedsricenoodles|vegfriedrice": "/images/restaurants/malasa-mangalya/friedsricenoodles/Veg Fried Rice.jpg",
  "malasamangalya|friedsricenoodles|vegschezwanrice": "/images/restaurants/malasa-mangalya/friedsricenoodles/Veg Schezwan Rice.jpg",
  "malasamangalya|friedsricenoodles|singaporerice": "/images/restaurants/malasa-mangalya/friedsricenoodles/Singapore Rice.jpg",
  "malasamangalya|friedsricenoodles|paneerfriedrice": "/images/restaurants/malasa-mangalya/friedsricenoodles/Paneer Fried Rice.jpg",
  "malasamangalya|noodles|veghakkanoodles": "/images/restaurants/dwaraka/noodles/VEG HAKKA NOODLES.jpg",
  "malasamangalya|noodles|vegschezwannoodles": "/images/restaurants/dwaraka/noodles/VEG SCHEZWAN NOODLES.jpg",
  "malasamangalya|dal|dalfry": "/images/restaurants/malasa-mangalya/dal.jsx fry.jpg",
  "malasamangalya|southindian|dalkolhapuri": "/images/restaurants/malasa-mangalya/southindian/puri.jpg",
  "malasamangalya|northindian|kajumasala": "/images/restaurants/malasa-mangalya/northindian/kaju masala.jpg",
  "malasamangalya|southindian|kajukolhapuri": "/images/restaurants/malasa-mangalya/southindian/puri.jpg",
  "malasamangalya|southindian|vegkolhapuri": "/images/restaurants/malasa-mangalya/southindian/puri.jpg",
  "malasamangalya|southindian|panneerkolhapuri": "/images/restaurants/malasa-mangalya/southindian/puri.jpg",
  "malasamangalya|southindian|mushroomkolhapuri": "/images/restaurants/malasa-mangalya/southindian/puri.jpg",
  "malasamangalya|northindiandishes|malaikofta": "/images/restaurants/hotel-nandini-deluxe/northindiandishes/Malai Kofta.jpg",
  "malasamangalya|northindian|vegpatiyala": "/images/restaurants/malasa-mangalya/northindian/veg patiyala.jpg",
  "malasamangalya|northindian|greenpeicemasala": "/images/restaurants/malasa-mangalya/northindian/green peice masala.jpg",
  "malasamangalya|northindian|channamasala": "/images/restaurants/malasa-mangalya/northindian/channa masala.jpg",
  "malasamangalya|tandoori|roti": "/images/restaurants/malasa-mangalya/tandoori/roti.jpg",
  "malasamangalya|tandoori|butterroti": "/images/restaurants/malasa-mangalya/tandoori/butter roti.jpg",
  "malasamangalya|southindianmealsrice|chapati": "/images/restaurants/malasa-mangalya/southindianmealsrice/Chapati Uta.jpg",
  "malasamangalya|ricebiriyani|vegbiriyani": "/images/restaurants/malasa-mangalya/ricebiriyani/Veg biryani.jpg",
  "malasamangalya|ricebiriyani|dalkichadi": "/images/restaurants/malasa-mangalya/ricebiriyani/dal kichadi.jpg",
  "malasamangalya|ricebiriyani|curdrice": "/images/restaurants/malasa-mangalya/ricebiriyani/curd rice.jpg",
  "malasamangalya|ricebiriyani|jeerarice": "/images/restaurants/malasa-mangalya/ricebiriyani/Jeera rice.jpg",
  "malasamangalya|rice|gheerice": "/images/restaurants/dwaraka/rice/GHEE RICE.jpg",
  "malasamangalya|hotbeverages|watermelonmilkshake": "/images/restaurants/malasa-mangalya/hotbeverages/milk.jpg",
  "malasamangalya|juicemilkshakes|apple": "/images/restaurants/malasa-mangalya/juicemilkshakes/Apple milkshake.jpg",
  "malasamangalya|juicemilkshakes|mango": "/images/restaurants/malasa-mangalya/juicemilkshakes/mango milkshake.jpg",
  "malasamangalya|juicemilkshakes|applemilkshake": "/images/restaurants/malasa-mangalya/juicemilkshakes/Apple milkshake.jpg",
  "malasamangalya|hotbeverages|chikkumilkshake": "/images/restaurants/malasa-mangalya/hotbeverages/milk.jpg",
  "malasamangalya|juicemilkshakes|mangomilkshake": "/images/restaurants/malasa-mangalya/juicemilkshakes/mango milkshake.jpg",
  "malasamangalya|hotbeverages|strawberrymilkshake": "/images/restaurants/malasa-mangalya/hotbeverages/milk.jpg",
  "malasamangalya|hotbeverages|rosemilkshake": "/images/restaurants/malasa-mangalya/hotbeverages/milk.jpg",
  "malasamangalya|hotbeverages|pistamilkshake": "/images/restaurants/malasa-mangalya/hotbeverages/milk.jpg",
  "malasamangalya|hotbeverages|coctailmilkshake": "/images/restaurants/malasa-mangalya/hotbeverages/milk.jpg",
  "malasamangalya|juicemilkshakes|faluda": "/images/restaurants/malasa-mangalya/juicemilkshakes/faluda.jpg",
  "malasamangalya|juicemilkshakes|faludahalf": "/images/restaurants/malasa-mangalya/juicemilkshakes/faluda.jpg",
  "malasamangalya|juicemilkshakes|lassi": "/images/restaurants/malasa-mangalya/juicemilkshakes/lassi.jpg",
  "malasamangalya|juicemilkshakes|buttermilk": "/images/restaurants/malasa-mangalya/juicemilkshakes/butter milk.jpg",
  "hotelnandinideluxe|hotbeverages|tea": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/Tea.jpg",
  "hotelnandinideluxe|hotbeverages|halftea": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/Half tea.jpg",
  "hotelnandinideluxe|hotbeverages|blacktea": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/Black tea.jpg",
  "hotelnandinideluxe|hotbeverages|spltea": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/Tea.jpg",
  "hotelnandinideluxe|hotbeverages|lemontea": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/Tea.jpg",
  "hotelnandinideluxe|hotbeverages|badammilk": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/Badam milk.jpg",
  "hotelnandinideluxe|hotbeverages|nescafe": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/Nescafe.jpg",
  "hotelnandinideluxe|hotbeverages|bournvita": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/Bournvita.jpg",
  "hotelnandinideluxe|hotbeverages|milk": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/milk.jpg",
  "hotelnandinideluxe|southindiansnack|idlis": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/idli.jpg",
  "hotelnandinideluxe|southindiansnack|idlip": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/idli.jpg",
  "hotelnandinideluxe|southindiansnack|idlivadas": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/idli.jpg",
  "hotelnandinideluxe|southindiansnack|idlivadap": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/idli.jpg",
  "hotelnandinideluxe|southindiansnack|uppittu": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/uppittu.jpg",
  "hotelnandinideluxe|southindiansnack|sheera": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/shira.jpg",
  "hotelnandinideluxe|southindiansnack|chowchowbhath": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/Chow Chow bath.jpg",
  "hotelnandinideluxe|southindiansnack|palav": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/Pulav.jpg",
  "hotelnandinideluxe|southindiansnack|puribhajis": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/puri bhaji.jpg",
  "hotelnandinideluxe|southindiansnack|puribhajip": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/puri bhaji.jpg",
  "hotelnandinideluxe|southindiansnack|plaindosa": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/plain dosa.jpg",
  "hotelnandinideluxe|southindian|masaladosa": "/images/restaurants/hotel-nandini-deluxe/southindian/masala-dosa.jpg",
  "hotelnandinideluxe|southindian|cuttmasaladosa": "/images/restaurants/hotel-nandini-deluxe/southindian/masala-dosa.jpg",
  "hotelnandinideluxe|southindiansnack|khalidosas": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/khali dosa.jpg",
  "hotelnandinideluxe|southindiansnack|khalidosap": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/khali dosa.jpg",
  "hotelnandinideluxe|southindiansnack|onionuttappa": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/onion uttappa.jpg",
  "hotelnandinideluxe|southindiansnack|oniontomatouttappa": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/onion Tomato uttappa.jpg",
  "hotelnandinideluxe|southindiansnack|mysoremasala": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/mysore masala.jpg",
  "hotelnandinideluxe|southindiansnack|paperdosa": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/paper dosa.jpg",
  "hotelnandinideluxe|southindian|buttermasaladosa": "/images/restaurants/hotel-nandini-deluxe/southindian/masala-dosa.jpg",
  "hotelnandinideluxe|main|tomatoomlet": "/images/restaurants/aras-grand/main/tomato omlet.jpg",
  "hotelnandinideluxe|main|ravadosa": "/images/restaurants/aras-grand/main/rava dosa.jpg",
  "hotelnandinideluxe|southindian|pannerbuttermasaladosa": "/images/restaurants/hotel-nandini-deluxe/southindian/masala-dosa.jpg",
  "hotelnandinideluxe|southindian|mashroombuttermasaladosa": "/images/restaurants/hotel-nandini-deluxe/southindian/masala-dosa.jpg",
  "hotelnandinideluxe|southindian|cheezmasaladosa": "/images/restaurants/hotel-nandini-deluxe/southindian/masala-dosa.jpg",
  "hotelnandinideluxe|thali|southindianmeals": "/images/restaurants/hotel-nandini-deluxe/thali/South Indian Meals.jpg",
  "hotelnandinideluxe|thali|northindianmeals": "/images/restaurants/hotel-nandini-deluxe/thali/North Indian Meals.jpg",
  "hotelnandinideluxe|southindianmealsrice|extrarice": "/images/restaurants/malasa-mangalya/southindianmealsrice/extra rice.jpg",
  "hotelnandinideluxe|thali|ricesambar": "/images/restaurants/hotel-nandini-deluxe/thali/Rice Sambar.jpg",
  "hotelnandinideluxe|soupitems|tomatosoup": "/images/restaurants/hotel-nandini-deluxe/soupitems/Tomato Soup.jpg",
  "hotelnandinideluxe|soupitems|sweetcornsoup": "/images/restaurants/hotel-nandini-deluxe/soupitems/Sweet Corn Soup.jpg",
  "hotelnandinideluxe|soupitems|sweetcornvegsoup": "/images/restaurants/hotel-nandini-deluxe/soupitems/Veg Soup.jpg",
  "hotelnandinideluxe|soupitems|vegsoup": "/images/restaurants/hotel-nandini-deluxe/soupitems/Veg Soup.jpg",
  "hotelnandinideluxe|soupitems|manchowsoup": "/images/restaurants/hotel-nandini-deluxe/soupitems/Manchow Soup.jpg",
  "hotelnandinideluxe|soupitems|palaksoup": "/images/restaurants/hotel-nandini-deluxe/soupitems/Palak Soup.jpg",
  "hotelnandinideluxe|southindiansnack|roastedpapad": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/Roasted Papad.jpg",
  "hotelnandinideluxe|starters|frypapad": "/images/restaurants/hotel-nandini-deluxe/starters/fry Papad.jpg",
  "hotelnandinideluxe|starters|masalapapad": "/images/restaurants/hotel-nandini-deluxe/starters/masala papad.jpg",
  "hotelnandinideluxe|starters|greensalad": "/images/restaurants/hotel-nandini-deluxe/starters/green salad.jpg",
  "hotelnandinideluxe|starters|fingerchips": "/images/restaurants/hotel-nandini-deluxe/starters/finger chips.jpg",
  "hotelnandinideluxe|starters|gobimanchurian": "/images/restaurants/hotel-nandini-deluxe/starters/Gobi Manchurian.jpg",
  "hotelnandinideluxe|starters|gobichilly": "/images/restaurants/hotel-nandini-deluxe/starters/Gobi chilly.jpg",
  "hotelnandinideluxe|starters|gobi65": "/images/restaurants/hotel-nandini-deluxe/starters/Gobi 65.jpg",
  "hotelnandinideluxe|starters|gobi65offry": "/images/restaurants/hotel-nandini-deluxe/starters/Gobi 65.jpg",
  "hotelnandinideluxe|starters|paneermanchurian": "/images/restaurants/hotel-nandini-deluxe/starters/paneer Manchurian.jpg",
  "hotelnandinideluxe|starters|paneerchilly": "/images/restaurants/hotel-nandini-deluxe/starters/paneer chilly.jpg",
  "hotelnandinideluxe|starters|paneer65": "/images/restaurants/hotel-nandini-deluxe/starters/paneer 65.jpg",
  "hotelnandinideluxe|starters|mashroommanchurian": "/images/restaurants/hotel-nandini-deluxe/starters/mashroom manchurian.jpg",
  "hotelnandinideluxe|starters|mashroomchilly": "/images/restaurants/hotel-nandini-deluxe/starters/mashroom chilly.jpg",
  "hotelnandinideluxe|starters|mashroom65": "/images/restaurants/hotel-nandini-deluxe/starters/mashroom 65.jpg",
  "hotelnandinideluxe|chinese|vegharabarakabab": "/images/restaurants/malasa-mangalya/chinese/veg harabara kabab.jpg",
  "hotelnandinideluxe|vegstarters|babycorntikka": "/images/restaurants/dwaraka/vegstarters/BABY CORN TIKKA.jpg",
  "hotelnandinideluxe|mushroomstarters|mashroomtikka": "/images/restaurants/dwaraka/mushroomstarters/MUSHROOM TIKKA.jpg",
  "hotelnandinideluxe|northindiandishes|dalfry": "/images/restaurants/hotel-nandini-deluxe/northindiandishes/Dal Fry.jpg",
  "hotelnandinideluxe|northindiandishes|daltadka": "/images/restaurants/hotel-nandini-deluxe/northindiandishes/Dal Tadka.jpg",
  "hotelnandinideluxe|northindiandishes|palakpaneer": "/images/restaurants/hotel-nandini-deluxe/northindiandishes/Palak Paneer.jpg",
  "hotelnandinideluxe|northindiandishes|paneerbuttermasala": "/images/restaurants/hotel-nandini-deluxe/northindiandishes/Paneer Butter Masala.jpg",
  "hotelnandinideluxe|northindiandishes|vegkadai": "/images/restaurants/hotel-nandini-deluxe/northindiandishes/Veg Kadai.jpg",
  "hotelnandinideluxe|maincourse|vegkofta": "/images/restaurants/dwaraka/maincourse/VEG KOFTA.jpg",
  "hotelnandinideluxe|northindiandishes|malaikofta": "/images/restaurants/hotel-nandini-deluxe/northindiandishes/Malai Kofta.jpg",
  "hotelnandinideluxe|northindiandishes|mixveg": "/images/restaurants/hotel-nandini-deluxe/northindiandishes/Mix Veg.jpg",
  "hotelnandinideluxe|maincourse|vegjaipuri": "/images/restaurants/dwaraka/maincourse/VEG JAIPURI.jpg",
  "hotelnandinideluxe|northindian|vegpatiyala": "/images/restaurants/malasa-mangalya/northindian/veg patiyala.jpg",
  "hotelnandinideluxe|maincourse|paneerpatiyala": "/images/restaurants/dwaraka/maincourse/PANEER PATIYALA.jpg",
  "hotelnandinideluxe|riceitems|plainrice": "/images/restaurants/hotel-nandini-deluxe/riceitems/Plain rice.jpg",
  "hotelnandinideluxe|rice|gheerice": "/images/restaurants/dwaraka/rice/GHEE RICE.jpg",
  "hotelnandinideluxe|riceitems|jeerarice": "/images/restaurants/hotel-nandini-deluxe/riceitems/Jeera rice.jpg",
  "hotelnandinideluxe|rice|curdrice": "/images/restaurants/dwaraka/rice/Curd Rice.jpg",
  "hotelnandinideluxe|riceitems|vegpulav": "/images/restaurants/hotel-nandini-deluxe/riceitems/Veg pulav.jpg",
  "hotelnandinideluxe|biryani|vegbiriyani": "/images/restaurants/dwaraka/biryani/Veg biryani.jpg",
  "hotelnandinideluxe|friedsricenoodles|vegfriedrice": "/images/restaurants/malasa-mangalya/friedsricenoodles/Veg Fried Rice.jpg",
  "hotelnandinideluxe|southindiansnack|paneerpulav": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/Pulav.jpg",
  "hotelnandinideluxe|riceitems|dalkhichdi": "/images/restaurants/hotel-nandini-deluxe/riceitems/Dal Khichdi.jpg",
  "hotelnandinideluxe|rice|paneerfriedrice": "/images/restaurants/dwaraka/rice/Paneer Fried Rice.jpg",
  "hotelnandinideluxe|biryani|paneerbiriyani": "/images/restaurants/dwaraka/biryani/Paneer Biriyani.jpg",
  "hotelnandinideluxe|biryani|mashroombiriyani": "/images/restaurants/dwaraka/biryani/Mashroom Biriyani.jpg",
  "hotelnandinideluxe|hotbeverages|steamrice": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/Tea.jpg",
  "hotelnandinideluxe|rice|onionchillyfriedrice": "/images/restaurants/dwaraka/rice/ONION CHILLI FRIED RICE.jpg",
  "hotelnandinideluxe|noodles|vegnoodles": "/images/restaurants/hotel-nandini-deluxe/noodles/Veg Noodles.jpg",
  "hotelnandinideluxe|noodles|veghakkanoodles": "/images/restaurants/hotel-nandini-deluxe/noodles/Veg Hakka Noodles.jpg",
  "hotelnandinideluxe|noodles|vegsehezwannoodles": "/images/restaurants/hotel-nandini-deluxe/noodles/Veg Sehezwan Noodles.jpg",
  "hotelnandinideluxe|tandooriitems|roti": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/roti.jpg",
  "hotelnandinideluxe|tandooriitems|butterroti": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/butter roti.jpg",
  "hotelnandinideluxe|tandooriitems|naan": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/butter naan.jpg",
  "hotelnandinideluxe|tandooriitems|butternaan": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/butter naan.jpg",
  "hotelnandinideluxe|tandooriitems|gralicbutternaan": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/butter naan.jpg",
  "hotelnandinideluxe|tandooriitems|parota": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/parota.jpg",
  "hotelnandinideluxe|tandooriitems|aluparota": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/parota.jpg",
  "hotelnandinideluxe|tandooriitems|paneerparota": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/parota.jpg",
  "hotelnandinideluxe|tandooriitems|vegstuffparota": "/images/restaurants/hotel-nandini-deluxe/tandooriitems/parota.jpg",
  "hotelnandinideluxe|chatsitems|freshlimejuice": "/images/restaurants/hotel-nandini-deluxe/chatsitems/Fresh Lime Juice.jpg",
  "hotelnandinideluxe|freshjuicemilkshake|lassi": "/images/restaurants/hotel-nandini-deluxe/freshjuicemilkshake/Lassi.jpg",
  "hotelnandinideluxe|freshjuicemilkshake|watermelonjuice": "/images/restaurants/hotel-nandini-deluxe/freshjuicemilkshake/Water Melon Juice.jpg",
  "hotelnandinideluxe|freshjuicemilkshake|applemlikshake": "/images/restaurants/hotel-nandini-deluxe/freshjuicemilkshake/Apple Mlik Shake.jpg",
  "hotelnandinideluxe|hotbeverages|chikkumilkshake": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/milk.jpg",
  "hotelnandinideluxe|hotbeverages|anarmilkshake": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/milk.jpg",
  "hotelnandinideluxe|freshjuicemilkshake|mangomilkshake": "/images/restaurants/hotel-nandini-deluxe/freshjuicemilkshake/Mango Milk Shake.jpg",
  "hotelnandinideluxe|hotbeverages|bananamilkshake": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/milk.jpg",
  "hotelnandinideluxe|hotbeverages|buttermilk": "/images/restaurants/hotel-nandini-deluxe/hotbeverages/milk.jpg",
  "hotelnandinideluxe|chatsitems|panipuri": "/images/restaurants/hotel-nandini-deluxe/chatsitems/Panipuri.jpg",
  "hotelnandinideluxe|chatsitems|bhelpuri": "/images/restaurants/hotel-nandini-deluxe/chatsitems/Bhel puri.jpg",
  "hotelnandinideluxe|chatsitems|shevpuri": "/images/restaurants/hotel-nandini-deluxe/chatsitems/shev puri.jpg",
  "hotelnandinideluxe|chatsitems|dahipuri": "/images/restaurants/hotel-nandini-deluxe/chatsitems/Dahi puri.jpg",
  "hotelnandinideluxe|chatsitems|pavabhaji": "/images/restaurants/hotel-nandini-deluxe/chatsitems/pav bhaji.jpg",
  "hotelnandinideluxe|chatsitems|splpavbhaji": "/images/restaurants/hotel-nandini-deluxe/chatsitems/pav bhaji.jpg",
  "shankaridlicenter|breakfastspecials|1plateidli3piece": "/images/restaurants/shankar-idli-center/breakfastspecials/plate idli.jpg",
  "shankaridlicenter|breakfastspecials|uddinvada": "/images/restaurants/shankar-idli-center/breakfastspecials/uddin vada.jpg",
  "dwaraka|breakfast|alupuri": "/images/restaurants/dwaraka/breakfast/Aloo Poori.jpg",
  "dwaraka|combos|dosaidlicombosmallmasaladosaminiidliravaidly": "/images/restaurants/dwaraka/combos/dosa_idli_combo.png",
  "dwaraka|soups|lemoncorindersoup": "/images/restaurants/dwaraka/soups/lemon_coriander_soup.png",
  "foodriderscafe|pizza|margherita": "/images/restaurants/foodriders-cafe/Margherita.png",
  "foodriderscafe|pizza|americanpizza": "/images/restaurants/foodriders-cafe/American Pizza.png",
  "foodriderscafe|pizza|mexicanpizza": "/images/restaurants/foodriders-cafe/Mexican Pizza.png",
  "foodriderscafe|pizza|paneertikapizza": "/images/restaurants/foodriders-cafe/Paneer Tika Pizza.png",
  "foodriderscafe|pizza|panjabitashan": "/images/restaurants/foodriders-cafe/Panjabi Tashan.png",
  "foodriderscafe|pizza|schezwandelight": "/images/restaurants/foodriders-cafe/Schezwan Delight.png",
  "foodriderscafe|pizza|themaya": "/images/restaurants/foodriders-cafe/The Maya.png",
  "foodriderscafe|pizza|vegdelight": "/images/restaurants/foodriders-cafe/Veg Delight.png",
  "foodriderscafe|snacks|fingerchips": "/images/restaurants/foodriders-cafe/Snacks & Beverages/Fingerchips.png",
  "foodriderscafe|snacks|paasta": "/images/restaurants/foodriders-cafe/Snacks & Beverages/Paasta.png",
  "foodriderscafe|snacks|redchillypaasta": "/images/restaurants/foodriders-cafe/Snacks & Beverages/Red Chilly Paasta.png",
  "foodriderscafe|snacks|coffeebru": "/images/restaurants/foodriders-cafe/Snacks & Beverages/Coffee.png",
  "foodriderscafe|snacks|water": "/images/restaurants/foodriders-cafe/Snacks & Beverages/Water.png",
  "arasgrand|southindian|idli": "/images/restaurants/aras-grand/main/IDLI.jpg",
  "arasgrand|southindian|idlivada": "/images/restaurants/aras-grand/main/IDLI VADA.jpg",
  "arasgrand|southindian|menduvada": "/images/restaurants/aras-grand/main/Medu Vada.jpg",
  "arasgrand|southindian|dahivada": "/images/restaurants/aras-grand/main/DAHI VADA.jpg",
  "arasgrand|southindian|mosaruavalakki": "/images/restaurants/aras-grand/main/MOSARAVALAKKI.jpg",
  "arasgrand|southindian|sheera": "/images/restaurants/aras-grand/main/SHEERA.jpg",
  "arasgrand|southindian|uppit": "/images/restaurants/aras-grand/main/UPPITTU.jpg",
  "arasgrand|southindian|purikurma": "/images/restaurants/aras-grand/main/PURI KURMA.jpg",
  "arasgrand|southindian|palav": "/images/restaurants/aras-grand/main/PALAV.jpg",
  "arasgrand|dosaitems|mysoremas": "/images/restaurants/aras-grand/main/Mysore Masala Dosa.jpg",
  "arasgrand|dosaitems|mysoremasala": "/images/restaurants/aras-grand/main/Mysore Masala Dosa.jpg",
  "arasgrand|dosaitems|akkidosa": "/images/restaurants/aras-grand/main/AKKI DOSA.jpg",
  "arasgrand|dosaitems|masaladosa": "/images/restaurants/aras-grand/main/masala dosa.jpg",
  "arasgrand|dosaitems|buttermasaladosa": "/images/restaurants/aras-grand/main/butter masala dosa.jpg",
  "arasgrand|dosaitems|onionuttappa": "/images/restaurants/aras-grand/main/onion uttappa.jpg",
  "arasgrand|dosaitems|ravamasaladosa": "/images/restaurants/aras-grand/main/rava dosa.jpg",
  "arasgrand|dosaitems|sadadosa": "/images/restaurants/aras-grand/main/sada  dosa.jpg",
  "arasgrand|starters|vegspringroll": "/images/restaurants/aras-grand/specials/Veg Spring Roll.jpeg",
  "arasgrand|starters|paneerpopcorn": "/images/restaurants/aras-grand/specials/Paneer Popcorn.jpeg",
  "arasgrand|starters|vegmomos": "/images/restaurants/aras-grand/specials/Veg Momos.jpeg",
  "basaveshwarkhanavali|lunch|rottiuta": "/images/restaurants/basaveshwar-khanavali/lunch/ROTTI UTA.jpeg",
  "basaveshwarkhanavali|lunch|chapatiuta": "/images/restaurants/basaveshwar-khanavali/lunch/CHAPATI UTA.jpeg",
  "davanagerebennedosecenter|specialties|bennedosesinglepiece": "/images/restaurants/davanagere-benne-dose-center/specialties/davanagere benne dosa.jpg",
  "davanagerebennedosecenter|specialties|singleidliwada": "/images/restaurants/davanagere-benne-dose-center/specialties/single idli vadaa.jpg",
  "davanagerebennedosecenter|specialties|doubleidliwada": "/images/restaurants/davanagere-benne-dose-center/specialties/single idli vadaa.jpg",
  "shankaridlicenter|breakfastspecials|plateidli": "/images/restaurants/shankar-idli-center/breakfastspecials/plate idli.jpg",
  "hotelnandinideluxe|southindiansnack|vadas": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/idli.jpg",
  "hotelnandinideluxe|southindiansnack|vadap": "/images/restaurants/hotel-nandini-deluxe/southindiansnack/idli.jpg",
  "hotelnandinideluxe|southindiansnack|masaladosa": "/images/restaurants/hotel-nandini-deluxe/southindian/masala-dosa.jpg",
  "hotelnandinideluxe|thali|chapatibhaji": "/images/restaurants/hotel-nandini-deluxe/thali/Chapati bhaji.jpg",
  "malasamangalya|southindian|vadaa": "/images/restaurants/malasa-mangalya/southindian/Vadaa.jpg",
  "malasamangalya|southindian|purikurma": "/images/restaurants/malasa-mangalya/southindian/Kurma puri.jpg",
  "malasamangalya|tandoori|butternaan": "/images/restaurants/malasa-mangalya/tandoori/butter naan.jpg"
};